spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true

        routes:
        # User Service Route
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - AddRequestHeader=X-Service-Name,user-service

        # Booking Service Route
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/booking-service/**
          filters:
            - AddRequestHeader=X-Service-Name,booking-service

springdoc:
  swagger-ui:
    urls:
      - name: User Service
        url: /api/user-service/v3/api-docs
      - name: Booking Service
        url: /api/booking-service/v3/api-docs
