spring:
  application:
    name: booking-service

eureka:
    client:
        serviceUrl:
            defaultZone: http://service-registry:8761/eureka/
            
springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html