spring:
    application:
        name: user-service

eureka:
    client:
        serviceUrl:
            defaultZone: http://service-registry:8761/eureka/

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /swagger-ui.html